title: "Quantum Transition Labs"
description: "Quantum-safe cryptography, secure architecture, and PQC migration services."

theme: jekyll-theme-cayman

markdown: kramdown
kramdown:
  input: GFM

include:
  - assets/css
  - _layouts

sass:
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag

baseurl: ""
url: "https://qtransitionlabs.com"
